### ISSUE TITLE
Merge into workshop repository

### ISSUE THREAD

**Issue by dleehr** [Reproducible-Science-Curriculum/2015-05-14-duke-materials#1]

**Comment by dleehr** [comment]
@hlapp Would it be helpful to merge this repo before the workshop begins?

**Comment by hlapp** [comment]
You mean into the workshop website repo? Good idea, yes!

**Comment by dleehr** [comment]
OK. We won't be able to re-use the bit.ly links but I'll subtree this into the repo for monday's workshop.

**Comment by dleehr** [comment]
Done with https://github.com/Reproducible-Science-Curriculum/2015-06-01-reproducible-science-idigbio/pull/1.
